# Generated by Django 4.0.5 on 2022-07-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_serial', models.CharField(blank=True, max_length=30)),
                ('meter_number', models.CharField(blank=True, max_length=30)),
                ('meter_status', models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE')], default='1', max_length=30)),
                ('created', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
                'db_table': 'meters',
                'ordering': ['created'],
            },
        ),
    ]
