# Generated by Django 4.0.4 on 2022-06-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.site'),
        ),
    ]
